package be.uantwerpen.fti.ei.space;
// Imports used for the sounds.
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import java.io.IOException;
/**
 * This class is used to control the special bullets generated by the player ship with a bonus and the sound.
 * @author Bavo Lesy
 * @version 1.0
 */
public abstract class SpecialBullets extends Entity{
    public abstract void Vis();
    int dyFreezeB = 15; // Speed of the bullets shot by the player.
    protected SoundComponent sound; // Contains different sounds (data).
    protected SoundSystem updateSound; // Contains the logic to play the sounds.
    public SpecialBullets() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        this.sound = new SoundComponent("freezeBeam");
        this.updateSound = new SoundSystem(sound);
    }
    /**
     * This method moves the special bullets.
     */
    public void moveFreezeBullets(){
        specialBulletY -= dyFreezeB;
    }
    /**
     * This method is used to play the sound.
     * @return sound of the player shooting special bullets.
     */
    public SoundSystem getUpdateSound(){
        return updateSound;
    } // Getter used to access the sound.



}
